[profile.default]
src = 'src'
out = 'out'
libs = ['lib']

verbosity = 2

rpc_endpoints = { mainnet = "https://rpc.ankr.com/eth", polygon = "https://rpc.ankr.com/polygon", avax = "https://rpc.ankr.com/avalanche" }
